import React from 'react';
import './globals.css';
import Header from '../components/Header';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }): JSX.Element {
  return (
    <html lang="en">
      <body className="bg-slate-900 text-slate-100">
        <div className="container mx-auto px-4">
          <Header />
          {children}
          </div>       
        </body>
    </html>
  )
}
